config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create destroy]

  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: [:show]

  post 'users/:id/follow', to: 'users#follow', as: 'follow'
  post 'users/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'users/:id/accept', to: 'users#accept', as: 'accept'
  post 'users/:id/decline', to: 'users#decline', as: 'decline'
  post 'users/:id/cancel', to: 'users#cancel', as: 'cancel'

  get 'posts/feed'
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :text, length: { maximum: 500 }, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :description, length: { maximum: 500 }
  validates :image, presence: true
  belongs_to :user

  has_one_attached :image
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  followability

  has_many :posts
  has_many :comments
  has_many :likes

  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show destroy]

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
      else
        format.html { redirect_to @comment.post, alert: 'Comment cannot be blank or longer than 500 characters.' }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to @comment.post, notice: 'Comment was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:text, :user_id, :post_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    @like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  before_action :authenticate_user!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = @post.comments.build
  end

  def feed
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
  
    if @post.user == current_user # Check if the post belongs to the current user
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    else
      # Handle unauthorized update attempt
      redirect_to root_path, alert: "You are not authorized to update this post."
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:image, :description, :user_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc)
  end

  def follow
    current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(current_user)
    redirect_back(fallback_location: root_path)
  end

  def unfollow
    current_user.unfollow(@user)
    redirect_back(fallback_location: root_path)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/comments/_comment.html.erb
<div id>
  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <script>
    function autoResize(textarea) {
      textarea.style.height = "auto";
      textarea.style.height = (textarea.scrollHeight) + "px";
    }
  </script>
</head>

<body>
  <%= form_with(model: comment) do |form| %>
    
    <%= form.text_area :text, style: "width: 600px;", oninput: "autoResize(this)" %>
    <br>
    <br>
    <%= form.submit class: "btn btn-primary " %>

    <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
    <%= form.text_field :post_id, type:"hidden" %>

    <br>
  <% end %>
</body>
</html>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <%= link_to "All Posts", root_path, class:"navbar-brand", style: "margin-left: 20px;" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent", style="margin-left: 20px; ">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        
      </li>
      <li class="nav-item">
        <%= link_to "New Post", new_post_path, class: "nav-link"%>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Feed", posts_feed_path, class: "nav-link"%>
        </li> 
        <li class="nav-item">
          <%= link_to "My Page", current_user, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <button class="btn btn-primary btn" onclick="window.location.href='<%= destroy_user_session_path %>'">Sign Out</button>
        </li> 
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link; btn btn-primary"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <script>
    function autoResize(textarea) {
      textarea.style.height = "auto";
      textarea.style.height = (textarea.scrollHeight) + "px";
    }
  </script>
</head>

<body>
  <div class="col-4" style="margin: auto; ">
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.text_field :user_id, type: "hidden", value: current_user.id %> 
    </div>

    <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
    </div>

    <br>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, style: "width: 100%;", oninput: "autoResize(this)" %>
    </div>

    <br>

    <div>
      <%= form.submit class: "btn btn-primary col-12" %>
    </div>
  <% end %>
  </div>
  </body>
  </html>

app/views/posts/_post.html.erb
<br>
<div class="username-container"> <h5><%= link_to post.user.email, post.user %><h5></div>
<div class="post-container">
  <%= image_tag(post.image, style: "object-fit: contain; width: 500px; height: 500px;") %>
  <%= link_to "", post, class:"post-link" %>
  <p>
  <div style="text-align: left"><%= post.description %></div>
</div>
<%= turbo_frame_tag dom_id(post, :like) do %>
  <div class="like-container" style="display: flex; align-items: center;">
    <span style="margin-right: 10px;">
      <% if user_signed_in? %>
        <% like = current_user.likes.find_by(post: post) %>
        <% if like.nil? %>
          <%= button_to "🤍", likes_path, params: { like: { post_id: post.id } }, method: :post, class: "btn btn-primary btn-light" %>
        <% else %>
          <%= button_to "❤️", like_path(like), method: :delete, class: "btn btn-primary btn-light" %>
        <% end %>
      <% else%>
      ⠀❤️⠀
      <% end %>
    </span>
    <%= "#{post.likes.count} #{'Like'.pluralize(post.likes.count)}" %>
  </div>
<% end %>
<%= turbo_frame_tag "post_#{post.id}" do %>
  <div class="buttons-container" style= "justify-content: flex-start; margin-left: 24px;">
      <%= "💬⠀⠀#{post.comments.count} #{'Comment'.pluralize(post.comments.count)}" %>
  </div>
<% end %>
<br>

app/views/posts/edit.html.erb
<div id="posts" class="text-center">
  <%= stylesheet_link_tag("post")%>
  <div>
  <p style="color: green"><%= notice %></p>  
  <div> 
  <h1>Editing post</h1>
  <br>
  <%= render "form", post: @post %>
  <br>
  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/feed.html.erb
<div class="text-center">
  <div>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>  
  <div>  
  
  <h1>Feed</h1>
  <br>


<% @posts.each do |post| %>
  <% if user_signed_in? %>
    <% if current_user.following?(post.user) %>
      <%= render post %>
      <br>
      <% post.comments.last(3).each do |comment| %>
        <div class="comment-container" style="display: flex; justify-content: space-between: 20px; align-items: center; margin-bottom: 5px;">
        <div style="text-align: left; flex: 1;">
          <%= "#{link_to(comment.user.email, user_path(comment.user))}: #{comment.text}".html_safe if comment.text.present?%>
        </div>
          <% if comment.user && current_user.id == comment.user.id %>
            <div class="delete-button">
              <%= button_to "🗑️", comment, method: :delete, class: "btn btn-primary btn-light" %>
            </div>
          <% end %>
        </div>
      <% end %>
      <% if post.comments.count > 3 %>
        <div class="comment-container" style="display: flex; justify-content: space-between: 20px; align-items: center; margin-bottom: 5px;">
          <p><%= link_to "...", post, class:"custom-link" %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <br>
<% end %>

app/views/posts/index.html.erb
<div class="text-center">
  <div>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>   
  <div> 

  <h1>All Posts</h1>
  <br>
  <br>

<% @posts.each do |post| %>
  <%= render post %>
    <% if user_signed_in? %>
      <% post.comments.last(3).each do |comment| %>
      <div class="comment-container">
        <div class="comment-text">
          <%= "#{link_to(comment.user.email, user_path(comment.user))}: #{comment.text}".html_safe if comment.text.present?%>
        </div>
        <% if comment.user && current_user.id == comment.user.id %>
          <div class="delete-button">
            <%= button_to "🗑️", comment, method: :delete, class: "btn btn-primary btn-light" %>
          </div>
        <% end %>
      </div>
      <% end %>
      <% if post.comments.count > 3 %>
        <div class="comment-container">
          <p><%= link_to "...", post, class:"custom-link" %></p>
        </div>
      <% end %>
    <% else %>
        <br>
    <% end %>
    <br>
    <br>
<% end %>

app/views/posts/myfeed.html.erb
<div id="posts" class="text-center">
  <%= stylesheet_link_tag("post")%>
  <div>
  <p style="color: green"><%= notice %></p>  
  <div>  
  <h1>My feed</h1>
  <br>
  <% @posts.each do |post| %>
    <% if user_signed_in? %>
      <% if current_user.following?(post.user) %>
        <%= render post %>
    <% end %>
  <% end %> 
<% end %> 
</div>

app/views/posts/new.html.erb
<div id="posts" class="text-center">
  <%= stylesheet_link_tag("post")%>
  <div>
  <p style="color: green"><%= notice %></p>  
  <div>  
  <h1>New Post</h1>
  <br>
  <div class="row"><%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class="text-center">
  <div>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
  <div>

<%= render @post %>
<div class= buttons-container>
  <%= link_to "Back ", posts_path, class: "btn btn-primary" %>
  <% if user_signed_in? %>
    <% if current_user.id == @post.user.id %>
      <div class="ml-2">
      <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>

      </div>
      <div class="ml-2">
        <%= button_to "Delete", @post, method: :delete, class: "btn btn-danger" %>
      </div>
    <% end %>
</div>
<br>

<%= turbo_frame_tag dom_id(@post, :comment) do %>
  <% @post.comments.each do |comment| %>
    <div class="comment-container">
      <div class="comment-text">
        <%= "#{link_to(comment.user.email, user_path(comment.user), target: '_blank')}: #{comment.text}".html_safe if comment.text.present?%>
      </div>
      <% if comment.user && current_user.id == comment.user.id %>
        <div class="delete-button">
          <%= button_to "🗑️", comment, method: :delete, class: "btn btn-primary btn-light" %>
        </div>
      <% end %>
    </div>
    <% end %>
      <p style="color: red"><%= alert %></p>
  <%= render "comments/form", comment: @comment %>
  <% end %> 
<% end %> 
</div>
<br>
<br>

app/views/users/show.html.erb
<div class="text-center">
  <div>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p> 
  <div>  

<turbo-frame id="user_profile">
  <% if @user.email != current_user.email %>
    <h1><%= @user.email %></h1>
    <% if current_user.following?(@user) %>
      <%= button_to "Unfollow", unfollow_path(@user), class: "btn btn-primary btn-danger", method: :post %>
    <% else %>
      <%= button_to "Follow", follow_path(@user), class: "btn btn-primary btn-success", method: :post %>
    <% end %>
  <% else %>
    <h1>My Page</h1>
    <%= current_user.email %>
    <br>
    <br>
  <% end %>
</turbo-frame>
<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <h5>Followers</h5>
      <% @user.followers.each do |follower| %>
          <p><b><%= link_to follower.email, follower %></b></p>
      <% end %>
  </div>
  <div class="col-5">
    <h5>Following</h5>
    <% @user.following.each do |following| %>
        <p><%= link_to following.email, following %></p>
    <% end %>
  </div>
</div>
<br>

<div class="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <br>
    <% post.comments.last(3).each do |comment| %>
      <div class="comment-container">
        <div class="comment-text">
          <%= "#{link_to(comment.user.email, user_path(comment.user))}: #{comment.text}".html_safe if comment.text.present? %>
        </div>
        <% if comment.user && current_user.id == comment.user.id %>
          <div class="delete-button">
            <%= button_to "🗑️", comment, method: :delete, class: "btn btn-primary btn-light" %>
          </div>
        <% end %>
      </div>
    <% end %>
      <% if post.comments.count > 3 %>
        <div class="comment-container">
          <p><%= link_to "...", post, class:"custom-link" %></p>
        </div>
      <% end %>
    <br>
    <br>
  <% end %>
</div>